In [2]:
import numpy as np

## The basics

Shift + Tab - Open function documentation 

#### One dimensional array

In [3]:
oned_array = np.array([1, 2, 3, 4], dtype='int8')
oned_array

array([1, 2, 3, 4], dtype=int8)

In [4]:
lst = [2, 3, 4]
lst

[2, 3, 4]

#### Two dimensional array

In [5]:
twod_array = np.array([[3, 4, 5], [9, 8, 7]])
twod_array

array([[3, 4, 5],
       [9, 8, 7]])

#### <span style="color:orange;">ndim</span> - Checks how many dimensional is our array 

In [6]:
oned_array.ndim

1

In [7]:
twod_array.ndim

2

#### <span style="color:orange;">shape</span> - Returns shape of n-dimensional array. In 2 or more dimensional array we have (rows, cols)

In [8]:
oned_array.shape

(4,)

In [9]:
twod_array.shape

(2, 3)

#### <span style="color:orange;">dtype</span> - Returns the type of elements in array

In [10]:
oned_array.dtype

dtype('int8')

#### <span style="color:orange;">itemsize</span> - Returns the size of an item in bytes
- int8 - 1 byte
- int64 - 8 bytes

In [11]:
oned_array.itemsize

1

#### <span style="color:orange;">nbytes</span> - Returns the size of the whole array in bytes

In [12]:
oned_array.nbytes

4

#### <span style="color:orange;">size</span> - Returns the length of array

In [13]:
oned_array.size

4

## Accessing arrays

In [14]:
arr = np.array([2, 7, 9, 4, 4, 6])

# arr[start:stop:step]
arr[1:4:2]

array([7, 4])

In [15]:
multidim_array = np.array([
    [12, 31, 24, 52, 98],
    [34, 1, 23, 87, 76]
])

In [16]:
multidim_array.shape

(2, 5)

In [17]:
# [row, col], it can be also slice on both sides
# [ 1:2, 4] - first and second row and fourth column
# [1, 2:4] - form first row second and fourth columns 
multidim_array[1, 4]

76

In [18]:
# get only one column
multidim_array[:, 2]

array([24, 23])

In [20]:
# get only one row
multidim_array[1, :]

array([34,  1, 23, 87, 76])

## Initialize different types of arrays

#### <span style="color:orange;">zeros</span> - Generates array from zeroes

In [21]:
np.zeros(4)

array([0., 0., 0., 0.])

In [24]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

#### <span style="color:orange;">ones</span> - Generates array from ones

In [25]:
np.ones((3, 2, 5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### <span style="color:orange;">full</span> - Generates array with given value

In [26]:
np.full((2, 2), 99)

array([[99, 99],
       [99, 99]])

In [28]:
# all _like functions takes exist array with his shape and manipulates it.
np.full_like(multidim_array, 100)

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

#### <span style="color:orange;">random</span> - Generates array with random values

In [29]:
np.random.rand(10)

array([0.69252985, 0.91989311, 0.17429458, 0.80500441, 0.51148262,
       0.14000145, 0.30417698, 0.61342197, 0.87718644, 0.47877595])

In [31]:
np.random.randn(10)

array([ 0.66390764,  0.24596298, -0.38016489,  1.94425801,  0.29268726,
        0.28676183, -0.42723146, -0.05695671,  0.34058492, -0.55819111])

In [32]:
# np.random.seed(42) - to prevent change of random generated number when notebook is running multiple times
np.random.randint(50, 100)

83

In [33]:
np.random.randint(50, 100, size=(3, 3))

array([[96, 80, 55],
       [94, 94, 56],
       [90, 96, 78]])

#### <span style="color:orange;">eye</span> - Returns matrix which main diagonal is with ones 

In [34]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Maths

In [35]:
my_arr = np.array([2, 3, 8, 12, 0])

In [36]:
my_arr + 2

array([ 4,  5, 10, 14,  2])

In [37]:
my_arr - 3

array([-1,  0,  5,  9, -3])

In [38]:
my_arr / 2

array([1. , 1.5, 4. , 6. , 0. ])

In [39]:
my_arr * 2

array([ 4,  6, 16, 24,  0])

In [40]:
my_arr ** 2

array([  4,   9,  64, 144,   0])

In [42]:
your_arr = np.array([4, 3, -1, 9, 12])

In [43]:
my_arr + your_arr

array([ 6,  6,  7, 21, 12])

In [44]:
my_arr - your_arr

array([ -2,   0,   9,   3, -12])

In [45]:
my_arr * your_arr

array([  8,   9,  -8, 108,   0])

In [46]:
my_arr / your_arr

array([ 0.5       ,  1.        , -8.        ,  1.33333333,  0.        ])

In [47]:
np.sin(my_arr)

array([ 0.90929743,  0.14112001,  0.98935825, -0.53657292,  0.        ])

## Linear algebra

In [48]:
mat1 = np.ones((2, 3))
mat1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [49]:
mat2 = np.full((3, 2), 2)
mat2

array([[2, 2],
       [2, 2],
       [2, 2]])

In [50]:
mat1 * mat2

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [51]:
np.matmul(mat1, mat2)

array([[6., 6.],
       [6., 6.]])

In [52]:
np.matmul(mat2, mat1)

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [53]:
# Find determinant
np.linalg.det(np.random.randint(2, 100, size=(3, 3)))

-132061.0000000002

## Statistics

In [54]:
stats = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [55]:
np.min(stats)

1

In [56]:
np.min(stats, axis=0)

array([1, 2, 3])

In [57]:
np.min(stats, axis=1)

array([1, 4])

In [58]:
np.max(stats)

6

- axis=0 - rows
- axis=1 - columns

In [59]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [60]:
np.sum(stats, axis=1)

array([ 6, 15])

In [61]:
np.average(stats)

3.5

In [63]:
np.average(stats, axis=1)

array([2., 5.])

## Reorganizing arrays

In [64]:
old_arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])
old_arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [65]:
old_arr.reshape((1, 8))

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [66]:
old_arr.reshape((8, 1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [68]:
old_arr.reshape((4, 2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [69]:
old_arr.reshape((2, 4))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

#### <span style="color:orange;">vstack</span> - Vertical stack of arrays

In [72]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

np.vstack([arr1, arr2])


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])