In [1]:
import numpy as np

## The basics

#### One dimensional array

In [4]:
oned_array = np.array([1, 2, 3, 4], dtype='int8')
oned_array

array([1, 2, 3, 4], dtype=int8)

In [3]:
lst = [2, 3, 4]
lst

[2, 3, 4]

#### Two dimensional array

In [5]:
twod_array = np.array([[3, 4, 5], [9, 8, 7]])
twod_array

array([[3, 4, 5],
       [9, 8, 7]])

#### <span style="color:orange;">ndim</span> - Checks how many dimensional is our array 

In [6]:
oned_array.ndim

1

In [7]:
twod_array.ndim

2

#### <span style="color:orange;">shape</span> - Returns shape of n-dimensional array. In 2 or more dimensional array we have (rows, cols)

In [8]:
oned_array.shape

(4,)

In [9]:
twod_array.shape

(2, 3)

#### <span style="color:orange;">dtype</span> - Returns the type of elements in array

In [10]:
oned_array.dtype

dtype('int8')

#### <span style="color:orange;">itemsize</span> - Returns the size of an item in bytes
- int8 - 1 byte
- int64 - 8 bytes

In [11]:
oned_array.itemsize

1

#### <span style="color:orange;">nbytes</span> - Returns the size of the whole array in bytes

In [12]:
oned_array.nbytes

4

#### <span style="color:orange;">size</span> - Returns the length of array

In [13]:
oned_array.size

4

## Accessing arrays

In [15]:
arr = np.array([2, 7, 9, 4, 4, 6])

# arr[start:stop:step]
arr[1:4:2]

array([7, 4])