# Principles of NumPy – Homework

### 1. Null Array

•	Read as input an integer N
•	Print a null array (consisting of zeros only) of length N

In [1]:
import numpy as np

In [2]:
n = int(input())

null_array = np.zeros(n)
print(null_array)

[0.]


## 2. Consecutive Array

Write a program using NumPy that:
•	Read as input **two integers** – **start number** and **end number**
•	Print an array ranging from start number to end number **inclusive**


In [3]:
start_number = int(input())
end_number = int(input())

arr = np.arange(start_number, end_number + 1)
print(arr)

[1 2]


## 3. Identity Matrix

Write a program using NumPy that:
•	Read an integer number N 
•	Print an identity matrix of size N


In [4]:
n = int(input())

identity_matrix = np.eye(n)
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 4. Evenly Spaced Array

Write a program using NumPy that:
•	Read  three integers – start, stop, and N
•	Prints an array of N with evenly spaced numbers between start and stop


In [5]:
start = int(input())
end = int(input())
n = int(input())

spaced_array = np.linspace(start, end, n)
print(spaced_array)

[4.  4.2 4.4 4.6 4.8 5. ]
